// <auto-generated />
using System;
using MVC_Entity_Framework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_Entity_Framework.Migrations
{
    [DbContext(typeof(MVC_Entity_FrameworkContext))]
    [Migration("20211004135037_123")]
    partial class _123
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18");

            modelBuilder.Entity("MVC_Entity_Framework.Models.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actvo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AutorForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaPrincipalForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriasSecundariaForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CuerpoForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EncabezadoForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("PalabrasClave")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AutorForeignKey");

                    b.HasIndex("CategoriaPrincipalForeignKey");

                    b.HasIndex("CategoriasSecundariaForeignKey");

                    b.HasIndex("CuerpoForeignKey")
                        .IsUnique();

                    b.HasIndex("EncabezadoForeignKey")
                        .IsUnique();

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Cuerpo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cuerpos");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Encabezado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Encabezados");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CuerpoForeignKey")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Orden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CuerpoForeignKey");

                    b.ToTable("Entradas");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArticuloId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaYHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Referencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ArticuloId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArticuloPrincipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticuloReferencial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.ToTable("Referencias");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRol")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassWord")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Articulo", b =>
                {
                    b.HasOne("MVC_Entity_Framework.Models.Autor", "Autor")
                        .WithMany("Articulos")
                        .HasForeignKey("AutorForeignKey");

                    b.HasOne("MVC_Entity_Framework.Models.Categoria", "CategoriaPrincipal")
                        .WithMany()
                        .HasForeignKey("CategoriaPrincipalForeignKey");

                    b.HasOne("MVC_Entity_Framework.Models.Categoria", "CategoriasSecundaria")
                        .WithMany()
                        .HasForeignKey("CategoriasSecundariaForeignKey");

                    b.HasOne("MVC_Entity_Framework.Models.Cuerpo", "Cuerpo")
                        .WithOne("Articulo")
                        .HasForeignKey("MVC_Entity_Framework.Models.Articulo", "CuerpoForeignKey");

                    b.HasOne("MVC_Entity_Framework.Models.Encabezado", "Encabezado")
                        .WithOne("Articulo")
                        .HasForeignKey("MVC_Entity_Framework.Models.Articulo", "EncabezadoForeignKey");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Entrada", b =>
                {
                    b.HasOne("MVC_Entity_Framework.Models.Cuerpo", "Cuerpo")
                        .WithMany("Entradas")
                        .HasForeignKey("CuerpoForeignKey");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Mensaje", b =>
                {
                    b.HasOne("MVC_Entity_Framework.Models.Articulo", "Articulo")
                        .WithMany("Mensajes")
                        .HasForeignKey("ArticuloId");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Referencia", b =>
                {
                    b.HasOne("MVC_Entity_Framework.Models.Articulo", null)
                        .WithMany("Referencias")
                        .HasForeignKey("ArticuloId");
                });

            modelBuilder.Entity("MVC_Entity_Framework.Models.Rol", b =>
                {
                    b.HasOne("MVC_Entity_Framework.Models.Usuario", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
